dataset:
  name: katorilab

data:
  processed_dir: processed_112_32
  split: default

artifact_path: "runs/20260201215901"

infer:
  # test_file_list: processed/splits/test_list.txt
  recall_ks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  targets: ["full", "img", "skel"]
  out_dir: "infer"
  sentence_transformer: stsb-xlm-r-multilingual
