# name: har-2way-model-training
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.5.*
  - torchvision
  - pytorch-cuda=12.1
  - numpy
  - pyyaml
  - tqdm
  - matplotlib
